name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Heroku CLI
      uses: actions/heroku@v9
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
    
    - name: Login to Heroku
      run: heroku login
      
    - name: Deploy to Heroku
      run: |
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/<book-recom-py>.git HEAD:main
